# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }
plugins: rubocop-rspec
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
AllCops:
  Exclude:
    - "inferno-tests/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
RSpec/ExampleLength:
  Enabled: false
RSpec/IncludeExamples:
  Enabled: true
