require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/patients", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PatientRecord. As you add validations to PatientRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:patient).clinical_attributes
  }

  let(:invalid_attributes) {
    { uuid: SecureRandom.uuid }
  }

  describe "GET /index" do
    it "renders a successful response" do
      PatientRecord.create! valid_attributes
      get patients_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      patient = PatientRecord.create! valid_attributes
      get patient_url(patient)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_patient_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      patient = PatientRecord.create! valid_attributes
      get edit_patient_url(patient)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Patient Record" do
        expect {
          post patients_url, params: { patient_record: valid_attributes }
        }.to change(PatientRecord, :count).by(1)
      end

      it "redirects to the created patient" do
        post patients_url, params: { patient_record: valid_attributes }
        expect(response).to redirect_to(patient_record_url(PatientRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Patient Record" do
        expect {
          post patients_url, params: { patient_record: invalid_attributes }
        }.not_to change(PatientRecord, :count)
      end

      it "renders a response with 400 status (i.e. to display the 'new' template)" do
        post patients_url, params: { patient_record: invalid_attributes }
        expect(response).to have_http_status(:bad_request) # new behavior for rails parameters `expect`
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
         { last_name: "TEST UPDATE" }
      }

      it "updates the requested patient" do
        patient = PatientRecord.create! valid_attributes
        patch patient_url(patient), params: { patient_record: new_attributes }
        patient.reload
        expect(patient.last_name).to eq("TEST UPDATE")
      end

      it "redirects to the patient" do
        patient = PatientRecord.create! valid_attributes
        patch patient_url(patient), params: { patient_record: new_attributes }
        patient.reload
        expect(response).to redirect_to(patient_record_url(patient))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 400 status (i.e. to display the 'edit' template)" do
        patient = PatientRecord.create! valid_attributes
        patch patient_url(patient), params: { patient_record: invalid_attributes }
        expect(response).to have_http_status(:bad_request) # new behavior for rails parameters `expect`
      end
    end
  end

  describe "POST /auto_match" do
    before do
      Setting.find_or_create_by!(key: "auto_match_threshold") do |s|
        s.description = "Auto-match threshold"
        s.value = 0.7
      end
    end

    context "with no matchable records" do
      it "creates no joins and redirects with notice" do
        create_list(:patient, 3)

        expect {
          post auto_match_patient_records_path
        }.not_to change(PatientJoin, :count)

        expect(response).to redirect_to(patient_records_path)
        expect(flash[:notice]).to match(/0 new link/)
      end
    end

    context "with corrupted duplicate records" do
      it "links each duplicate back to its original" do
        original = PatientRecord.create_random!
        PatientRecord.simulate_corruption(original, records_to_generate: 2, randomness: 0.3)

        expect {
          post auto_match_patient_records_path
        }.to change(PatientJoin, :count).by(2)

        expect(flash[:notice]).to match(/2 new link/)
      end
    end

    context "when records are already linked" do
      it "is idempotent — a second run creates no additional joins" do
        original = PatientRecord.create_random!
        PatientRecord.simulate_corruption(original, records_to_generate: 2, randomness: 0.3)

        post auto_match_patient_records_path

        expect {
          post auto_match_patient_records_path
        }.not_to change(PatientJoin, :count)

        expect(flash[:notice]).to match(/0 new link/)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested patient" do
      patient = PatientRecord.create! valid_attributes
      expect {
        delete patient_url(patient)
      }.to change(PatientRecord, :count).by(-1)
    end

    it "redirects to the patients list" do
      patient = PatientRecord.create! valid_attributes
      delete patient_url(patient)
      expect(response).to redirect_to(patients_url)
    end
  end
end
